import pygame
import pygame.sprite
from pygame.locals import *

# Constants used troughout the game
##########################

# General Game constants
WINDOWWIDTH = 1000
WINDOWHEIGHT = 600
WINDOW_SCREEN = Rect(0, 0, WINDOWWIDTH, WINDOWHEIGHT)
FPS = 60

GAME_NAME = 'NAsteroids'
CAPTION = GAME_NAME

STARTING_LEVEL = 1

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)


TEXT_COLOR = WHITE
BACKGROUND_COLOR = BLACK

# Player constants
PLAYER_START_X = WINDOWWIDTH//2
PLAYER_START_Y = WINDOWHEIGHT//2
PLAYER_DIAMETER = 20

PLAYER_ROTATE_SPEED = 5
PLAYER_ACC = 0.2
PLAYER_BREAK_DEACC = -0.25
PLAYER_MAX_SPEED = 10
PLAYER_COLOR = (153, 0, 0, 0.7)
PLAYERWIDTH = 50

PLAYER_RESPAWN_TIME_MS = 5 * 1000
PLAYER_SPAWN_SAFE_TIME_MS = 3 * 1000
PLAYER_STARTING_LIVES = 4

# Rotation constants
ROTATE_CLOCKWISE = 1
ROTATE_NONE = 0
ROTATE_COUNTER_CLOCKWISE = -1


# Meteorite
METEROITE_COLOR = (222,184,135)
METEROITE_SCORE = 10

# Asteroid
ASTEROID_RADIUS = 50
ASTEROID_SHATTER_LEVEL = 2
ASTEROID_SHATTER_FACTOR = 2
ASTEROID_COLOR = (169,169,169)
ASTEROID_SCORE = 10
ASTEROID_HP = 1
ASTEROID_SPLIT_DOUBLE_CHANCE = 10
ASTEROID_SPAWN_SLIME_CHANCE = 7

# Cluster Asteroid
CLUSTER_ASTEROID_RADIUS = ASTEROID_RADIUS * 2
CLUSTER_ASTEROID_SHATTER_LEVEL = 1
CLUSTER_ASTEROID_SHATTER_FACTOR = 8
CLUSTER_ASTEROID_SCORE = 50
CLUSTER_ASTEROID_HP = 1

# Slimes
SLIME_RADIUS = 15
SLIME_COLOR = GREEN
SLIME_HP = 1
SLIME_SCORE = 25
SLIME_MAX_VELOCITY = 2
SLIME_ACC = 0.2

# Bullets
BULLET_RADIUS = 4
BULLET_VELOCITY = 12
BULLET_DURATION_MS = 500
BULLET_COLOR = RED

# Level constants
BASE_LEVEL_SPRITE_COUNT = 6

# Info constants
GAME_INFO_FONT_SIZE = 30
GAME_INFO_BIG_FONT_SIZE = 60
GAME_INFO_MARGINS = 20
GAME_INFO_BASE_X = GAME_INFO_MARGINS
GAME_INFO_BASE_Y = GAME_INFO_MARGINS

TEXT_DISPLAY_TIME_MS = 3 * 1000
##########################
